### ISSUE TITLE
Potential Bug: Kakariko Gate Guard GZ U 1.2

### ISSUE THREAD

**Issue by Flare278** [glankk/gz#66] opened 2021-05-21 16:43 UTC
I'm not sure if this is a corruption or an actual bug. Every time I talk to the gate guard in Kakariko Village he always opens the gate, but when he asks you to go to the market to buy a mask for him, his dialogue stops midway through and you are frozen in place once you hit the A button. I'm currently using Bizhawk 2.6.4 on Windows while using the GLideN64 core. I have re-downloaded the practice rom and it's software a few times, but the problem persisted. I have also tested the same rom with Japanese text in the same sequence and it works perfectly fine. I have also tested 1.1 and 1.0 in English text and those work perfectly fine as well. I have also tested different settings and cores on my emulator to check if it was the emulator or the rom itself. No luck there. It's either something wrong with the rom itself, or I might have to use a different emulator. I will include some images for reference. Has anyone else ran into this issue?

![Frozen In Place](https://user-images.githubusercontent.com/84587001/119171123-2497ee80-ba32-11eb-9a27-24e0408c114b.PNG)
![Gate Guard](https://user-images.githubusercontent.com/84587001/119171126-25308500-ba32-11eb-988c-f48f4cdef811.PNG)

**Comment by Flare278** [comment] 2021-05-21 17:05
How to replicate the bug:
Open the GZ 1.2 U rom.
Go over to Kakariko Village.
Talk to the Kakariko Gate guard with Zelda's Letter.
The guard's dialogue will cut short. [Bug # 1]
Close the text box.
Link will be frozen in place. [Bug # 2]

**Comment by glankk** [comment] 2021-05-21 17:40
I've confirmed that this happens on BizHawk, but I could not recreate it on N64 or Project64, which indicates that it's an emulator bug in BizHawk. It's pretty weird and I'd like to know what's going on, but other than the fact the only known way to recreate the bug at the moment involves gz, there's no indication that gz is the cause of the bug. I'm closing this issue until there's more evidence to suggest otherwise.

**Comment by Flare278** [comment] 2021-05-21 17:41
Ok. Thanks for the input.

**Closed by glankk** 2021-05-21 17:40 UTC

**Comment by flagrama** [comment] 2021-05-21 18:02
Is this still an issue in a more modern mupen64plus-core emulator like [Retroarch's Mupen64Plus Next core](https://github.com/libretro/mupen64plus-libretro-nx) or the [m64p emulator by Logan](https://github.com/loganmc10/m64p)?

Bizhawk is still based on a release of mupen64plus from 2015, while the Next libretro core should be using an up-to-date one. I'm pretty sure Bizhawk also doesn't use the dynamic recompiler, so you'd have to make sure to try using the Pure Interpreter or Cached Interpreter how ever you try it. Next defaults to the new dynamic recompiler, and m64p should default to the cached interpreter from my understanding.

**Comment by Flare278** [comment] 2021-05-21 18:57
So, I got the rom working on Project64. You were right. It was an issue with Bizhawk. Thank you for looking into the issue and thank you for your time.

**Comment by flagrama** [comment] 2021-05-21 19:09
I'd still like someone to confirm with a modern mupen64plus-core emu so that this bug can be reported to them properly if it is still an issue. I can't easily test BizHawk being as I'm on Linux or I'd do it myself.

**Comment by glankk** [comment] 2021-05-24 11:41
I've tested mupen64plus-core 2.5.0 on 64-bit dynarec, it does not seem to be affected.
